name: Deploy to Railway

on:
  push:
    branches:
      - main # O la rama que uses para tu código principal, por ejemplo 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19 # ¡Importante! Usamos Java 19 según tu proyecto
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Railway
        on:
          push:
            branches:
              - main

        jobs:
          deploy:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout code
                uses: actions/checkout@v4

              - name: Set up JDK 19
                uses: actions/setup-java@v4
                with:
                  java-version: '19'
                  distribution: 'temurin'
                  cache: maven

              - name: Build with Maven
                run: mvn clean package -DskipTests

              - name: Install Railway CLI and Deploy
                run: |
                  curl -fsSL https://railway.app/install.sh | sh # Instala la CLI de Railway
                  railway login --token ${{ secrets.RAILWAY_TOKEN }} # Inicia sesión con tu token
                  railway up --service CitaSaludFeature3---Backend --project tu-project-id-de-railway # Despliega tu servicio
                env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} # token en github